spring.kafka.bootstrap-servers=${BOOTSTRAP_SERVER_URL:localhost:9092}
consumer.topic=${REGISTERS_DELTA_TOPIC:registers-delta}
consumer.group-id=${GROUP_ID:registers-delta-consumer}
consumer.max-attempts=${MAX_ATTEMPTS:5}
consumer.backoff-delay=${BACKOFF_DELAY:100}
consumer.concurrency=${CONCURRENT_LISTENER_INSTANCES:10}

management.health.mongodb.enabled=false
management.endpoints.access.default=read_only
management.endpoints.web.exposure.include=health
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=healthcheck
management.endpoint.health.show-details=never

management.opentelemetry.enabled=${OTEL_LOG_ENABLED:false}
management.opentelemetry.logging.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/logs
management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/traces
management.otlp.metrics.export.url=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/metrics

transaction-id-salt=${TRANSACTION_ID_SALT:salt}

api.api-key=${API_KEY:testkey}
api.api-url=${API_LOCAL_URL:http://localhost:8888}

server.port=${PORT:8081}
